name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    name: Nix Flake Check
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix with Determinate Installer
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            accept-flake-config = true
            experimental-features = nix-command flakes

      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check flake formatting
        run: nix fmt -- --check .

      - name: Check flake
        uses: DeterminateSystems/flake-checker-action@main

      - name: Build all outputs
        run: nix flake check

      - name: Build packages
        run: |
          nix build .#grafana
          nix build .#prometheus
          nix build .#loki
          nix build .#tempo
          nix build .#alloy
          nix build .#grafana-stack

      - name: Test individual apps
        run: |
          echo "Testing app metadata and executability..."
          nix run .#grafana -- --version
          nix run .#prometheus -- --version
          nix run .#loki -- --version || echo "Loki version check may not be supported"
          nix run .#tempo -- --version
          nix run .#alloy -- --version

      - name: Test template generation
        run: |
          echo "Testing Nix flake templates..."
          mkdir -p /tmp/template-test
          cd /tmp/template-test
          nix flake init -t ${{ github.workspace }}#default
          nix flake check

  build-matrix:
    name: Build on ${{ matrix.system }}
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        include:
          - system: x86_64-linux
            os: ubuntu-22.04
          - system: aarch64-darwin
            os: macos-14
          - system: x86_64-darwin
            os: macos-13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix with Determinate Installer
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            accept-flake-config = true
            experimental-features = nix-command flakes

      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build development shell
        run: nix develop --command echo "Development shell works!"

      - name: Check if flake builds
        run: nix build .#packages.${{ matrix.system }}.default

  # Flox integration tests disabled for now - Flox not available in CI
  # TODO: Re-enable when Flox is available or we have a workaround

  integration-tests:
    name: Integration Tests - Live Stack
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix with Determinate Installer
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            accept-flake-config = true
            experimental-features = nix-command flakes

      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Start Grafana Stack in background
        run: |
          echo "🚀 Starting complete observability stack..."
          # Start the stack in background with timeout
          timeout 300 nix run .#grafana-stack &
          STACK_PID=$!
          echo "Stack PID: $STACK_PID"
          echo $STACK_PID > /tmp/stack.pid

          # Wait for services to start
          echo "⏳ Waiting for services to become ready..."
          for i in {1..60}; do
            echo "Attempt $i/60..."
            if curl -sf http://localhost:3000/api/health 2>/dev/null; then
              echo "✅ Grafana is ready!"
              break
            fi
            if curl -sf http://localhost:9090/-/ready 2>/dev/null; then
              echo "✅ Prometheus is ready!"
              break
            fi
            sleep 5
          done

      - name: Test service endpoints
        run: |
          echo "🔍 Testing service endpoints..."

          # Test Grafana health
          echo "Testing Grafana..."
          if curl -sf http://localhost:3000/api/health; then
            echo "✅ Grafana health check passed"
          else
            echo "⚠️  Grafana health check failed (may still be starting)"
          fi

          # Test Prometheus readiness
          echo "Testing Prometheus..."
          if curl -sf http://localhost:9090/-/ready; then
            echo "✅ Prometheus readiness check passed"
          else
            echo "⚠️  Prometheus readiness check failed (may still be starting)"
          fi

          # Test that ports are actually open
          echo "Testing port availability..."
          if ss -tuln | grep -q ":3000 "; then
            echo "✅ Port 3000 (Grafana) is open"
          fi
          if ss -tuln | grep -q ":9090 "; then
            echo "✅ Port 9090 (Prometheus) is open"
          fi

      - name: Cleanup
        if: always()
        run: |
          echo "🧹 Cleaning up background processes..."
          if [ -f /tmp/stack.pid ]; then
            PID=$(cat /tmp/stack.pid)
            kill -TERM $PID || true
            sleep 5
            kill -KILL $PID || true
          fi
          # Kill any remaining grafana/prometheus processes
          pkill -f grafana || true
          pkill -f prometheus || true
          pkill -f loki || true
          pkill -f tempo || true
          pkill -f alloy || true

  security:
    name: Security Checks
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix with Determinate Installer
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            accept-flake-config = true
            experimental-features = nix-command flakes

      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Run security audit
        run: |
          echo "🔍 Running security audit on Nix flake dependencies..."
          nix flake metadata --json | jq '.locks.nodes[] | select(.locked.type == "github") | {owner: .locked.owner, repo: .locked.repo, rev: .locked.rev}'