name: Publish tagged release to FlakeHub

on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-*"

jobs:
  flakehub-publish:
    name: Publish to FlakeHub
    runs-on: ubuntu-22.04
    permissions:
      id-token: write # Required for authenticating against FlakeHub
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ (inputs.tag != null) && format('refs/tags/{0}', inputs.tag) || '' }}

      - name: Install Nix with Determinate Installer
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Validate flake before publishing
        run: |
          nix flake check
          echo "✅ Flake validation passed"

      - name: Publish to FlakeHub
        uses: DeterminateSystems/flakehub-push@main
        with:
          visibility: public
          tag: ${{ github.ref_name }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          body: |
            ## 🚀 New Release: ${{ github.ref_name }}

            This release has been automatically published to [FlakeHub](https://flakehub.com).

            ### 📦 Installation

            **Using Nix Flakes:**
            ```bash
            nix run "https://flakehub.com/f/OWNER/grafana-nix/${{ github.ref_name }}.tar.gz"
            ```

            **Adding to your flake.nix:**
            ```nix
            {
              inputs = {
                grafana-nix.url = "https://flakehub.com/f/OWNER/grafana-nix/${{ github.ref_name }}.tar.gz";
              };
            }
            ```

            ### 🔧 Quick Start

            Try the Grafana stack locally:
            ```bash
            nix develop "https://flakehub.com/f/OWNER/grafana-nix/${{ github.ref_name }}.tar.gz"
            ```

            Full documentation is available in the repository README.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}